# Generated by Django 4.2.3 on 2023-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(max_length=50),
        ),
    ]
