# Generated by Django 4.2.3 on 2023-08-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='users_paid_for',
            field=models.ManyToManyField(related_name='expenses_paid_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
