# Generated by Django 4.2.3 on 2023-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
